### ISSUE TITLE
Can you put out the model code that generates your dataset?

### ISSUE THREAD

**Issue by mmppllhaha** [r-zemblys/gazeNet#1]
Your work is great and enlightening to me. But when I read the code, I found that the network model of generating data set in the paper is not given. Do you plan to give the code？

thank you！

**Comment by r-zemblys** [comment]
Model for generating training data can be found here: [gazeGenNet](https://github.com/r-zemblys/gazeGenNet/tree/master/logdir/model_final)

**Comment by mmppllhaha** [comment]
Thanks very much!
